name: ZMusic
main: me.zhenxin.zmusic.ZMusicBukkit
version: ${version}
api-version: '1.13'
author: 真心
description: 真心音乐系统
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  zm:
    usage: /zm help
    description: 主命令
    aliases:
      - zmusic
      - music
permissions:
  zmusic.use:
    default: true
    description: 普通玩家使用权限
  zmusic.bypass:
    default: op
    description: 绕过冷却和扣钱权限
  zmusic.playall:
    default: op
    description: 全服点歌权限
  zmusic.admin:
    default: op
    description: 管理员权限
