blank_issues_enabled: false
contact_links:
  - name: QQ 群
    url: https://jq.qq.com/?_wv=1027&k=9Xs1RMt5
    about: 加入我们的 QQ 交流群. 快速反馈问题, 并与其他用户交流.
  - name: Discord
    url: https://discord.gg/twQgJNufYn
    about: Ask questions and discuss with other ZMusic users in real time.