name: Dev Build

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/**"
      - "gradle/libs.versions.toml"
      - "gradle/wrapper/gradle-wrapper.properties"
      - "gradle.properties"
      - "**/src/**"
      - "**/build.gradle.kts"
      - "settings.gradle.kts"
      - "gradle.properties"
    branches:
      - "v4"
  pull_request:
    branches:
      - "v4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew clean build
      - uses: actions/upload-artifact@v4
        with:
          name: 'ZMusic Dev'
          path: |
            zmusic-bukkit/build/libs/*.jar
            zmusic-bungee/build/libs/*.jar
            zmusic-velocity/build/libs/*.jar